// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChkc-Hp8alN_IGMpeARkdQbcIAWpQpAck',
    appId: '1:77789232625:web:06b0c660f983976c17d850',
    messagingSenderId: '77789232625',
    projectId: 'cashflow-423301',
    authDomain: 'cashflow-423301.firebaseapp.com',
    storageBucket: 'cashflow-423301.appspot.com',
    measurementId: 'G-BJT6KHLQRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDa5tVEWOSGuGhlo5pAow2c7qhO5WB2R8',
    appId: '1:77789232625:android:6ab52844f64d9fe517d850',
    messagingSenderId: '77789232625',
    projectId: 'cashflow-423301',
    storageBucket: 'cashflow-423301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR1zUblxJIhlM--24gvPE0JLraf5rbk8U',
    appId: '1:77789232625:ios:a02a3f787136afd917d850',
    messagingSenderId: '77789232625',
    projectId: 'cashflow-423301',
    storageBucket: 'cashflow-423301.appspot.com',
    iosClientId: '77789232625-rlmmmbl2fhadkmgk7jt3l7c9e52equnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashflowApp',
  );
}
